### ISSUE TITLE
How can i use this project

### ISSUE THREAD

**Issue by fabiojansenbr** [chrispoulter/halcyon-api#1]
Hi Chris.

Congratulations for the Project, is working fine. I have some questions, if you can help-me.

I can use this Project, to rename-it and use on another Project ?
How can i re-create this API from zero? On the webapi template of visual studio 2017, using asp.net core, there's no options to use "individual user account". how you implement this?

Can you give me a tip to do the same?

And a final doubt is, where i can obtain the:

                 "Audience": "<JWT Audience>",
		"Authority": "<JWT Authority>",
		"SigningPassword": "<JWT Signing Certificate Password>"

Thank you

**Comment by chrispoulter** [comment]
Hi Fábio,

This project glues together Web API, ASP.NET Identity and OpenIddict. 

It’s all completely custom code so there is no Visual Studio template for it.

Feel free to copy / rename as needed.

Here are the settings you will need to get the project to run locally:

```
"Jwt": {
		"Audience": "http://localhost:8082/",
		"Authority": "http://localhost:8082/",
		"SigningPassword": "mqaC7UVcNhSN"
	}

```
When deploying you will need to update the “Audience” and “Authority” to match the environment you are deploying to.

You will also need to substitute the signing certificate included in the project with one of your own and update the “Signing Password” to match.

Thanks,
Chris
